### ISSUE TITLE
Syntax error: The `bg-dark-2` class does not exist. If `bg-dark-2` is a custom class, make sure it is defined within a `@layer` directive. (134:3)

### ISSUE THREAD

**Issue by AymanBoumait** [adrianhajdin/threads#1]
I copied the files exactly as provided but I keep getting this error:

 132 | /* Tab */
  133 | .tab {
> 134 |   @apply flex min-h-[50px] flex-1 items-center gap-3 bg-dark-2 text-light-2 data-[state=active]:bg-[#0e0e12] data-[state=active]:text-light-2 !important;
      |   ^
  135 | }
  136 | 
  
   132 | /* Tab */
  133 | .tab {
> 134 |   @apply flex min-h-[50px] flex-1 items-center gap-3 bg-dark-2 text-light-2 data-[state=active]:bg-[#0e0e12] data-[state=active]:text-light-2 !important;
      |   ^
  135 | }
  136 |

**Comment by AymanBoumait** [comment]
yes, as I said I copied from JS files directly

**Comment by Suryanshu1005** [comment]
@AymanBoumait I figured it has something to do with tailwind configurations. I got different but it is still related to Tailwind. You can see it here #2

**Comment by prakharsharma13** [comment]
did anyone solved it?

**Comment by Crazyhaller** [comment]
> did anyone solved it?

Even I am looking for the solution, its not getting any of its styling for me either

**Comment by JyotiSuman09** [comment]
Try copying next.config.js and tailwind.config.js files from github gist

**Comment by AymanBoumait** [comment]
> @AymanBoumait I figured it has something to do with tailwind configurations. I got different but it is still related to Tailwind. You can see it here #2

so u solved it?

**Comment by AymanBoumait** [comment]
> Refere
I am copying it from the gist I even tried to copy it from the github repo

**Comment by AymanBoumait** [comment]
> Try copying next.config.js and tailwind.config.js files from github gist


I am copying it from the gist I even tried to copy it from the github repo

**Comment by Crazyhaller** [comment]
> Try copying next.config.js and tailwind.config.js files from github gist

Tried, it still doesn't work, is it working for you?

**Comment by Dev-mininos** [comment]
Just copy the content of tailwind.config.js and globals.css and then restart the server

**Comment by Crazyhaller** [comment]
> Just copy the content of tailwind.config.js and globals.css and then restart the server

Tried it all man see what my screen is looking like #6

**Comment by Crazyhaller** [comment]
Guys the navbar not getting its style issue for me was because i mistakenly used jsx instead of tsx for the topbar file name, i just switched it to tsx and now its working for me, so if you have any similar typo fix it

**Comment by asayushranjansinha** [comment]
I had a similar issue in the globals.css file. After searching for it I found out that this usually happens because of some extra spaces that are added by IDEs for better formatting. So try to copy paste the exact code and do not format. This might help [Stack over flow](https://stackoverflow.com/q/67892366)

**Comment by pritishbhakat** [comment]
Step 1: copy the globals.css from git repo
Step 2: copy the tailwind.config.js from git repo
npm install tailwindcss-animate

**Comment by AymanBoumait** [comment]
> Step 1: copy the globals.css from git repo Step 2: copy the tailwind.config.js from git repo npm install tailwindcss-animate

That worked, thank you so much.

**Comment by ShoveetSingh** [comment]
> did anyone solved it?

Simply copy paste this line "npm install tailwindcss-animate" into ur terminal and then write "npm run dev"

**Comment by msal95** [comment]
> npm install tailwindcss-animate

delete .next folder
then restart the server, it'll work

**Comment by Ardak200** [comment]
check the file extension on tailwind config, I had ts file, and when I changed it to js and then restarted the server, styles got applied

**Comment by Sarina606** [comment]
I have the same problem and I tried everything you said here but nothing works for me. I still get this error.

./app/globals.css:8:5
Syntax error: C:\Users\OneDrive\Desktop\New folder\threads\app\globals.css The `bg-dark-1` class does not exist. If `bg-dark-1` is a custom class, make sure it is defined within a `@layer` directive.

   6 |   /* main */
   7 |   .main-container {
>  8 |     @apply flex min-h-screen flex-1 flex-col items-center bg-dark-1 px-6 pb-10 pt-28 max-md:pb-32 sm:px-10;
     |     ^
   9 |   }
  10 | 

Can you please help me too?
