### ISSUE TITLE
Error: ClerkInstanceContext not found

### ISSUE THREAD

**Issue by jaydeeprana049** [adrianhajdin/threads#10]
How to slove this please help.

**Comment by UDogg** [comment]
+1 Couldn't proceed after this error.

**Comment by UDogg** [comment]
`
// in ./app/(root)/layout.tsx
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "../globals.css";
import LeftSidebar from "@/components/shared/LeftSidebar";
import Bottombar from "@/components/shared/Bottombar";
import RightSidebar from "@/components/shared/RightSidebar";
import Topbar from "@/components/shared/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Threads",
  description: "A Next.js 13 Meta Threads application",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang='en'>
        <body className={inter.className}>
          <Topbar />

          <main className='flex flex-row'>
            <LeftSidebar />
            <section className='main-container'>
              <div className='w-full max-w-4xl'>{children}</div>
            </section>
            {/* @ts-ignore */}
            <RightSidebar />
          </main>

          <Bottombar />
        </body>
      </html>
    </ClerkProvider>
  );
}
`

**Comment by vraj79** [comment]
thankyou very much

**Comment by jaydeeprana049** [comment]
> ```
> // in ./app/(root)/layout.tsx
> import React from "react";
> import type { Metadata } from "next";
> import { Inter } from "next/font/google";
> import { ClerkProvider } from "@clerk/nextjs";
> import { dark } from "@clerk/themes";
> 
> import "../globals.css";
> import LeftSidebar from "@/components/shared/LeftSidebar";
> import Bottombar from "@/components/shared/Bottombar";
> import RightSidebar from "@/components/shared/RightSidebar";
> import Topbar from "@/components/shared/Topbar";
> 
> const inter = Inter({ subsets: ["latin"] });
> 
> export const metadata: Metadata = {
>   title: "Threads",
>   description: "A Next.js 13 Meta Threads application",
> };
> 
> export default function RootLayout({
>   children,
> }: {
>   children: React.ReactNode;
> }) {
>   return (
>     <ClerkProvider
>       appearance={{
>         baseTheme: dark,
>       }}
>     >
>       <html lang='en'>
>         <body className={inter.className}>
>           <Topbar />
> 
>           <main className='flex flex-row'>
>             <LeftSidebar />
>             <section className='main-container'>
>               <div className='w-full max-w-4xl'>{children}</div>
>             </section>
>             {/* @ts-ignore */}
>             <RightSidebar />
>           </main>
> 
>           <Bottombar />
>         </body>
>       </html>
>     </ClerkProvider>
>   );
> }
> ```

Bro Thanks man

**Comment by YONK17544** [comment]
> How to slove this please help.

You need to wrap ClerkProvider in both of the layout.tsx. Hope this helps!

**Comment by nan0hard** [comment]
Simply wrap your html which is present in (root)/layout.tsx with <ClerkProvider>

**Comment by Devilshree123** [comment]
Thank you. It helped...!

**Comment by erciktiburak** [comment]
**app > (auth) > layout.tsx > RootLayout**
**For the solution**, _you need to wrap a ClerkProvider in the RootLayout method:_

```
export default function RootLayout({ 
    children 
}: { 
    children: React.ReactNode 
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${inter.className} bg-dark-1`}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}
```
