### ISSUE TITLE
Module '"react-hook-form"' has no exported member 'useForm'

### ISSUE THREAD

**Issue by phucho0237** [adrianhajdin/threads#11]
![image](https://github.com/adrianhajdin/threads/assets/88989555/5cdfb896-0b1e-467d-8613-8518da8b3b43)

package.json: https://sourceb.in/52b3r46SXe

**Comment by Ky-Ling** [comment]
Did you npm install the type of react-hook-form library?

**Comment by phucho0237** [comment]
I generated "ui" folder with shadcn/ui, so it must be installed.

**Comment by phucho0237** [comment]
Never mind, I restarted my VSCode and the error go away.
