### ISSUE TITLE
After signin when page redirects to "/" this error accured

### ISSUE THREAD

**Issue by Rahaman270** [adrianhajdin/threads#16]
![error](https://github.com/adrianhajdin/threads/assets/110724571/83f9e0db-99ce-4034-a457-b4d5e1795de8)

**Comment by mentionworld** [comment]
hi @Rahaman270  you need to wrap you root layout.tsx file's <html></html> inside <ClerkProvider> component

![image](https://github.com/adrianhajdin/threads/assets/58510407/2ac6794b-ca88-4d3b-aad3-8e14ea626824)

**Comment by PARSA-00-55** [comment]
> hi @Rahaman270 you need to wrap you root layout.tsx file's inside component
> 
> Hope this will fix your issue.
> 
> cc; @adrianhajdin ![image](https://user-images.githubusercontent.com/58510407/258600039-2ac6794b-ca88-4d3b-aad3-8e14ea626824.png)

it worked .. thank you so much

**Comment by yugaldekate** [comment]
Wrap the (root)/layout/page.tsx with ClerkProvider.

import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>  
  );
}

**Comment by Rahaman270** [comment]
@mentionworld Thank You Very much bro. Issue Solved.
