### ISSUE TITLE
My  <OrganizationSwitcher/> is not shown 

### ISSUE THREAD

**Issue by Manmit124** [adrianhajdin/threads#17]
![Screenshot 2023-08-05 234454](https://github.com/adrianhajdin/threads/assets/112580293/8ebb1091-07e5-430a-8f5f-76177bcd3d30)

**Comment by Ky-Ling** [comment]
The reason you did not see the OrganizationSwitcher in your application is that you did not enable the organization in your clerk, to solve this problem, just go to your dashboard of the clerk, click the organization tab, and enable it, then the problem will get solved. 

![image](https://github.com/adrianhajdin/threads/assets/68088901/54b29047-d38a-4cb4-931f-f1481e751863)

**Comment by Manmit124** [comment]
Thanks bro
