### ISSUE TITLE
Error: ClerkInstanceContext not found

### ISSUE THREAD

**Issue by yuvraj042003** [adrianhajdin/threads#19]
This is my code and I try to import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider >
      <html lang='en'>
        <body className={`${inter.className} bg-dark-1`}>{children}</body>
      </html>
    </ClerkProvider>
  );
} 

I have trying diffrent ways But I can't solve this error. Please help me imidiatly

**Comment by Ky-Ling** [comment]
Please refer to #3 to get more information about the solution

**Comment by yuvraj042003** [comment]
Thank you so much But After Adding This Our code is not working and No data are shown in the application. 
This is code of root folder import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
} 

And this code of auth  folder 
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider >
      <html lang='en'>
        <body className={`${inter.className} bg-dark-1`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
![Uploading photod.PNG…]()

**Comment by Ky-Ling** [comment]
I did not see you wrap the ClerkProvider into your layout.tsx file in auth and root folder, did you miss some code you provide above?

**Comment by yuvraj042003** [comment]
This is my auth Layout.tsx code 
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Threads",
  description: "A Next.js 13 Meta Threads application",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
 And This is my Root Folder layout.tsx import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}

**Comment by yuvraj042003** [comment]
![Layout_Auth](https://github.com/adrianhajdin/threads/assets/81462095/9454ff49-da34-48b0-8956-5d18f85011cd)
![Layout_root](https://github.com/adrianhajdin/threads/assets/81462095/800878b5-0a0b-4785-8a7c-90e9e166c667)

**Comment by yuvraj042003** [comment]
If you have need any file.Plz tell us I provide as soon as possible. And Thank you  so much For help us.

**Comment by NamanMalhotra1706** [comment]
Yuvraj if You are Still facing this error : ClerkInstanceContext not found :- I saw your code Ss, You didn't import metadata and I didn't saw any other error in that but I recommend you to use the following code in your both layout.tsx files that is in (auth) and (root):

import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Threads Clone",
  description: "A Next.js 13 Meta Threads Application Clone",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={`${inter.className} bg-dark-1`}>{children}</body>
      </html>
    </ClerkProvider>
  );
}

If you are still facing any error please let me know

**Comment by yuvraj042003** [comment]
Yes I update my code. Thanks for help me Now workingmy code

**Comment by erciktiburak** [comment]
**app > (auth) > layout.tsx > RootLayout**
**For the solution**, _you need to wrap a ClerkProvider in the RootLayout method:_

```
export default function RootLayout({ 
    children 
}: { 
    children: React.ReactNode 
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${inter.className} bg-dark-1`}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}
```

**Comment by pcardo-prosal** [comment]
I have the same issue. My layout.tsx is exactly as @erciktiburak commented.
It was a repository that was working, but wen we move it to a TurboRepo monorepo, it starts to throw the error
