### ISSUE TITLE
Error: Failed to create/update user: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms

### ISSUE THREAD

**Issue by JyotiSuman09** [adrianhajdin/threads#20]
![Screenshot 2023-08-06 115123](https://github.com/adrianhajdin/threads/assets/84245491/70f1daaa-2012-4629-a578-aa7d9b14dfa1)

I'm unable to create entry in db...

**Comment by JyotiSuman09** [comment]
![Screenshot 2023-08-06 121815](https://github.com/adrianhajdin/threads/assets/84245491/5fb3e833-4f92-4cd1-925a-a269146abaab)


I think i did the mistake here in line no 9. it should be if(isConnected) not if(!isConnected)

**Comment by JyotiSuman09** [comment]
Issue resolved.

**Comment by rayvinith** [comment]
but still i think you will get error
