### ISSUE TITLE
OrganizationSwitcher is Not visible on the Navbar. 

### ISSUE THREAD

**Issue by Suryanshu1005** [adrianhajdin/threads#26]
Did anyone else have an issue where they can't get OrganizationSwitcher on the Topbar? 
![image](https://github.com/adrianhajdin/threads/assets/59340699/2a8e2d05-db98-4eaa-883d-866989c0bdc4)

![image](https://github.com/adrianhajdin/threads/assets/59340699/0e0b9ff7-9481-4fe6-8d3a-1eb5b8f32c53)

Any help is really appreciated :-)

**Comment by AymanBoumait** [comment]
try this one:
`<OrganizationSwitcher 
                appearance={{
                    baseTheme: dark,
                    elements: {
                        organizationSwitcherTrigger: "py-2 px-4"
                    }`

**Comment by Manmit124** [comment]
JUST GO ON THE WEBSITE (CLERK) AND ENABLE THE ORGNIZATION

**Comment by Suryanshu1005** [comment]
Alright guys, it was just some rendering issue with the tailwindcss. I started appearing automatically later. 

Thank you all for the help tho <3
