### ISSUE TITLE
404 Error Can you please help me out

### ISSUE THREAD

**Issue by vamshi99145** [adrianhajdin/threads#27]
- event compiled successfully in 498 ms (257 modules)
INFO: Clerk: The request to / is being redirected because there is no signed-in user, and the path is not included in `ignoredRoutes` or `publicRoutes`. To prevent this behavior, choose one of:

1. To make the route accessible to both signed in and signed out users, add "/" to the `publicRoutes` array passed to authMiddleware
2. To prevent Clerk authentication from running at all, add "/" to the `ignoredRoutes` array passed to authMiddleware
3. Pass a custom `afterAuth` to authMiddleware, and replace Clerk's default behavior of redirecting unless a route is included in publicRoutes

For additional information about middleware, please visit https://clerk.com/docs/nextjs/middleware
(This log only appears in development mode, or if `debug: true` is passed to authMiddleware)

**Comment by AymanBoumait** [comment]
go to middleware.ts in the root and update authMiddleware with this:

`export default authMiddleware({
    publicRoutes: ['/', '/api/webhook/clerk'],
    ignoredRoutes: ['/api/webhook/clerk'],
});`

**Comment by rayvinith** [comment]
see basically 404 error comes when that page doesn't exist , so basically you need to check that whether you have wriiten code properly or not . It'st debugging process carry on you will

**Comment by vamshi99145** [comment]
Thanks

**Comment by yang2674** [comment]
4. 
`-- Options debug, {
  "debug": true,
  "beforeAuth": false,
  "afterAuth": false
}
-- {
  "auth": "{\"sessionClaims\":null,\"sessionId\":null,\"session\":null,\"userId\":null,\"user\":null,\"actor\":null,\"orgId\":null,\"orgRole\":null,\"orgSlug\":null,\"organization\":null,\"isPublicRoute\":true,\"isApiRoute\":false}",
  "debug": {
    "debug": true,
    "signInUrl": "/sign-in",
    "request": {
      "sourcePage": "/middleware",
      "experimental_clerkUrl": "http://localhost:3000/sign-up"
    },
    "apiKey": "",
    "secretKey": "sk_test",
    "audience": "",
    "apiUrl": "https://api.clerk.dev",
    "apiVersion": "v1",
    "frontendApi": "epic-molly-16.clerk.accounts.dev",
    "proxyUrl": "",
    "publishableKey": "pk_test_ZXBpYy1tb2xseS0xNi5jbGVyay5hY2NvdW50cy5kZXYk",
    "isSatellite": false,
    "domain": "",
    "jwtKey": "",
    "searchParams": {},
    "clientUat": "0",
    "host": "localhost:3000",
    "referrer": "http://localhost:3000/sign-up",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "status": "signed-out",
    "reason": "standard-signed-out",
    "message": ""
  }
}
-- {
  "mergedHeaders": "{\"x-middleware-next\":\"1\"}"
}
-- Added x-clerk-debug on request

 `
`-- Options debug, {
  "debug": true,
  "beforeAuth": false,
  "afterAuth": false
}
-- {
  "auth": "{\"sessionClaims\":null,\"sessionId\":null,\"session\":null,\"userId\":null,\"user\":null,\"actor\":null,\"orgId\":null,\"orgRole\":null,\"orgSlug\":null,\"organization\":null,\"isPublicRoute\":true,\"isApiRoute\":false}",
  "debug": {
    "debug": true,
    "signInUrl": "/sign-in",
    "request": {
      "sourcePage": "/middleware",
      "experimental_clerkUrl": "http://localhost:3000/sign-up"
    },
    "apiKey": "",
    "secretKey": "sk_test",
    "audience": "",
    "apiUrl": "https://api.clerk.dev",
    "apiVersion": "v1",
    "frontendApi": "epic-molly-16.clerk.accounts.dev",
    "proxyUrl": "",
    "publishableKey": "pk_test_ZXBpYy1tb2xseS0xNi5jbGVyay5hY2NvdW50cy5kZXYk",
    "isSatellite": false,
    "domain": "",
    "jwtKey": "",
    "searchParams": {},
    "clientUat": "0",
    "host": "localhost:3000",
    "referrer": "http://localhost:3000/sign-up",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "status": "signed-out",
    "reason": "standard-signed-out",
    "message": ""
  }
}
-- {
  "mergedHeaders": "{\"x-middleware-next\":\"1\"}"
}
-- Added x-clerk-debug on request

 `

**Comment by ferric-sol** [comment]
if using next, make sure trailingSlashes: false in next.config.js, it's next doing the redirects not clerk

**Comment by nzt867** [comment]
@hmongdev , did you find the solution?

**Comment by FahadAminShovon** [comment]
Hi, 
It's mostly because of your middleware configuration

try copy pasting this config and see if it works for you


```ts
import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";

const isPublicRoute = createRouteMatcher([
  "/api/webhooks",
  "/sign-in(.*)",
  "/sign-up(.*)",
  "/",
]);

export default clerkMiddleware((auth, req) => {
  if (!isPublicRoute(req)) {
    auth().protect();
  }
});

export const config = {
  matcher: ["/((?!.*\\..*|_next).*)", "/", "/(api|trpc)(.*)"],
};
```

I am using 
```json
    "@clerk/nextjs": "^5.1.4",
     "next": "14.2.3",
```
