### ISSUE TITLE
Unhandled Runtime Error -> Error: ClerkInstanceContext not found

### ISSUE THREAD

**Issue by Ky-Ling** [adrianhajdin/threads#3]
I just finished the basic setup with clerk authentication, but when I run my application with localhost:3000, I got this Unhandled Runtime Error, did I do something wrong with the setup? I am looking for someone's help, thanks!

![image](https://github.com/adrianhajdin/threads/assets/68088901/48563443-9b55-46be-86cb-0caa7981177e)

**Comment by phucho0237** [comment]
Me too, same error
![image](https://github.com/adrianhajdin/threads/assets/88989555/98aa2b74-5300-42d7-8ef1-552167177595)

**Comment by Manmit124** [comment]
fix: Wrap your application in layout.tsx(both in auth and root folders!)

**Comment by SRINJAYDASGUPTA-Git** [comment]
> I just finished the basic setup with clerk authentication, but when I run my application with localhost:3000, I got this Unhandled Runtime Error, did I do something wrong with the setup? I am looking for someone's help, thanks!
> 
> ![image](https://user-images.githubusercontent.com/68088901/258431867-48563443-9b55-46be-86cb-0caa7981177e.png)



> Wrap your application in layout.tsx

I am new to TypeScript.... can you please tell me hoe to do that........😅
Thanks in advance

**Comment by Ky-Ling** [comment]
Also, do not use the UserButton component on the page.tsx file under (root) folder can solve the problem temporarily

![image](https://github.com/adrianhajdin/threads/assets/68088901/721ce6c8-0bca-481a-b33a-ea5f023d8898)

**Comment by Ky-Ling** [comment]
> > Wrap your application in layout.tsx
> 
> I am new to TypeScript.... can you please tell me hoe to do that........😅 Thanks in advance

![image](https://github.com/adrianhajdin/threads/assets/68088901/315abe45-256e-4c06-861c-a7a25567e922)
You need to wrap the ClerkProvider into the layout.tsx file of (root ) folder

**Comment by SRINJAYDASGUPTA-Git** [comment]
> > > Wrap your application in layout.tsx
> > 
> > 
> > I am new to TypeScript.... can you please tell me hoe to do that........😅 Thanks in advance
> 
> ![image](https://user-images.githubusercontent.com/68088901/258438228-315abe45-256e-4c06-861c-a7a25567e922.png) You need to wrap the ClerkProvider into the layout.tsx file of (root ) folder

Thanks a lot
Its working
😁😁😁

**Comment by phucho0237** [comment]
> > > Wrap your application in layout.tsx
> > 
> > 
> > I am new to TypeScript.... can you please tell me hoe to do that........😅 Thanks in advance
> 
> ![image](https://user-images.githubusercontent.com/68088901/258438228-315abe45-256e-4c06-861c-a7a25567e922.png) You need to wrap the ClerkProvider into the layout.tsx file of (root ) folder

Working too, thanks!
![image](https://github.com/adrianhajdin/threads/assets/88989555/e503a9ff-4024-446f-af9f-7b110682bf5b)

**Comment by touraye** [comment]
> Also, do not use the UserButton component on the page.tsx file under (root) folder can solve the problem temporarily
> 
> ![image](https://user-images.githubusercontent.com/68088901/258437667-721ce6c8-0bca-481a-b33a-ea5f023d8898.png)

Sure I have commented on mine and it works

**Comment by jaydeeprana049** [comment]
> > > Wrap your application in layout.tsx
> > 
> > 
> > I am new to TypeScript.... can you please tell me hoe to do that........😅 Thanks in advance
> 
> ![image](https://user-images.githubusercontent.com/68088901/258438228-315abe45-256e-4c06-861c-a7a25567e922.png) You need to wrap the ClerkProvider into the layout.tsx file of (root ) folder

bro thanks alot

**Comment by jurabek105** [comment]
> > > Wrap your application in layout.tsx
> > 
> > 
> > I am new to TypeScript.... can you please tell me hoe to do that........😅 Thanks in advance
> 
> ![image](https://user-images.githubusercontent.com/68088901/258438228-315abe45-256e-4c06-861c-a7a25567e922.png) You need to wrap the ClerkProvider into the layout.tsx file of (root ) folder

Thanks a lot, it worked

**Comment by shivamgond420** [comment]
![Screenshot 2023-08-08 084234](https://github.com/adrianhajdin/threads/assets/136161872/96ad0170-3042-4749-9d3f-1d7839947f44)
thanks for help ,well done bro

**Comment by Tuong-Duy-Anh** [comment]
I follow the guide to fix the issue but new issue orcur as in the image
![image](https://github.com/adrianhajdin/threads/assets/94125196/b8b13fac-1fe3-401e-b173-a248cdc45054)

**Comment by RajSharma877** [comment]
> > > Wrap your application in layout.tsx
> > 
> > 
> > I am new to TypeScript.... can you please tell me hoe to do that........😅 Thanks in advance
> 
> ![image](https://user-images.githubusercontent.com/68088901/258438228-315abe45-256e-4c06-861c-a7a25567e922.png) You need to wrap the ClerkProvider into the layout.tsx file of (root ) folder



> > > > Wrap your application in layout.tsx
> > > 
> > > 
> > > I am new to TypeScript.... can you please tell me hoe to do that........😅 Thanks in advance
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/68088901/258438228-315abe45-256e-4c06-861c-a7a25567e922.png) You need to wrap the ClerkProvider into the layout.tsx file of (root ) folder
> 
> Thanks a lot, it worked

It worked for me too thanks

**Comment by RajSharma877** [comment]
Thanks for help

**Comment by oyugibear** [comment]
for some strange reason, the userButton component doesn't show after I put the clerkProvider but it's in the user. I'm also new to typescript. could somebody please show me where the error may be.

![Screenshot 2023-09-08 at 17 00 53](https://github.com/adrianhajdin/threads/assets/65049957/cf32904e-4853-421d-b667-659ad82df9cb)
![Screenshot 2023-09-08 at 17 01 24](https://github.com/adrianhajdin/threads/assets/65049957/c857e737-ed2d-4f82-828a-d2c4ebf65030)
![Screenshot 2023-09-08 at 17 01 48](https://github.com/adrianhajdin/threads/assets/65049957/fbc3cd9b-c73b-4ecf-86b1-96c882254609)
![Screenshot 2023-09-08 at 17 02 14](https://github.com/adrianhajdin/threads/assets/65049957/e26eec30-66a5-49e9-9fbc-43e74585f6bb)

**Comment by Harsh-Ojha** [comment]
> > > Wrap your application in layout.tsx
> > 
> > 
> > I am new to TypeScript.... can you please tell me hoe to do that........😅 Thanks in advance
> 
> ![image](https://user-images.githubusercontent.com/68088901/258438228-315abe45-256e-4c06-861c-a7a25567e922.png) You need to wrap the ClerkProvider into the layout.tsx file of (root ) folder

Thanks a lot.

**Comment by yhoungdev** [comment]
I fixed this issues by provider the ClerkProvider with a Higher Order Component 



```typescript
import { ClerkProvider } from "@clerk/nextjs";
import React from "react";

export function withClerkProvider(Component: any) {
	return function WrappedComponent(props: React.JSX.IntrinsicAttributes) {
		return (
			<ClerkProvider>
				<Component {...props} />
			</ClerkProvider>
		);
	};
}

```

**Comment by yhoungdev** [comment]
@hmzi67 has your problem been solved ?

**Comment by hmzi67** [comment]
Yeah it is solve
Thankyou so much brother

**Comment by erciktiburak** [comment]
**app > (auth) > layout.tsx > RootLayout**
**For the solution**, _you need to wrap a ClerkProvider in the RootLayout method:_

```
export default function RootLayout({ 
    children 
}: { 
    children: React.ReactNode 
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${inter.className} bg-dark-1`}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    )
}
```
