### ISSUE TITLE
No styling (Tailwind CSS) applied to Threads application

### ISSUE THREAD

**Issue by dophotography** [adrianhajdin/threads#31]
Hi, guys! I am stucked on the moment when we add Bottom, Top and etc. components and tried to output a "Home" message on the main page. The problem is that I made everything as in tutorial (repo is right down there). Finnaly, I got everything worked, but all the stylings didn't applied despite the fact that I wrote all the `className` correct. Maybe I have some `typescript.config` problems or etc., because my `tailwind.config` is copied from gist repo as well as global.css is copied from the final repo. I'll attach my `package.json` to check dependencies.

Here are some parts of my code. I would appretiate very much if someone would see my code and help me to fix this. Idk what exactly happened, maybe tailwind is not loaded, maybe it's just not applying. Thanks!

P.S. I also have this error when i open `tailwind.config` file under the `module` word (pic attached): 

> 'tailwind.config.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.

My repo: https://github.com/dophotography/threads

**(root)/page.tsx:**
![image](https://github.com/adrianhajdin/threads/assets/102299301/f19fdaf7-b93c-4677-aeb9-2deae74f8060)

**(root)/layout.tsx:**
![image](https://github.com/adrianhajdin/threads/assets/102299301/d59f1b92-eeeb-4cc9-80f0-4ba71d571e04)

**package.json:**
![image](https://github.com/adrianhajdin/threads/assets/102299301/3e6dcfde-720a-4439-b43f-1da5de948dd5)

Tailwind.config error:
![image](https://github.com/adrianhajdin/threads/assets/102299301/7ab93542-b9dd-48fd-a01c-79c4e97ec923)

My web output:
![image](https://github.com/adrianhajdin/threads/assets/102299301/6dc240ee-1aff-4fe5-9a87-c1db5c387353)

UPD: 
**tsconfig.json:**
![image](https://github.com/adrianhajdin/threads/assets/102299301/c883a4b9-0fd1-4851-9c9d-fd3c0263a4b2)

**Comment by AymanBoumait** [comment]
did you copy the tailwind.config.css as it is?

**Comment by dophotography** [comment]
> did you copy the tailwind.config.css as it is?

exactly as it is, no changes

**Comment by AymanBoumait** [comment]
try importing this:
`import { Component} from 'react'; `

**Comment by AymanBoumait** [comment]
try importing this:
`import { Component } from 'react'; `

**Comment by dophotography** [comment]
> try importing this: `import { Component } from 'react'; `

you mean, to add this to my layout.tsx in (root) dir?

**Comment by dophotography** [comment]
> @dophotography I think you haven't import globals.css in layout.tsx. Try importing `import "../globals.css";`

sure, it was the problem :) very stupid one, thank you for help!
