### ISSUE TITLE
Styling issue with shadcn components

### ISSUE THREAD

**Issue by stardustdev** [adrianhajdin/threads#32]
I followed the tutorial but all form elements are still in light theme. Anybody is facing same issue?

![image](https://github.com/adrianhajdin/threads/assets/53919399/c376afb0-25b0-4f7b-9129-4cfd002fa5b4)

**Comment by yuvraj042003** [comment]
I need your help?? Plz help me when I paste this command **npx shadcn-ui@latest add form** So I get error How can you install it.

**Comment by yuvraj042003** [comment]
> I need your help?? Plz help me when I paste this command **npx shadcn-ui@latest add form** So I get error How can you install it.

I have try diffrent ways but not  get soluction plz help me

**Comment by yuvraj042003** [comment]
![by using node terminal](https://github.com/adrianhajdin/threads/assets/81462095/17d348cd-e846-41fa-bd86-62cab039e7bc)
Errror

**Comment by Ky-Ling** [comment]
> ![by using node terminal](https://user-images.githubusercontent.com/81462095/258981310-17d348cd-e846-41fa-bd86-62cab039e7bc.PNG) Errror

Did you try this command before, also you may need to remove **node** before **npx**?

![image](https://github.com/adrianhajdin/threads/assets/68088901/cd12ecd5-60ba-41d9-ae35-2db7f3cfe1af)

**Comment by Ky-Ling** [comment]
> I followed the tutorial but all form elements are still in light theme. Anybody is facing same issue?
> 
> ![image](https://user-images.githubusercontent.com/53919399/258934643-c376afb0-25b0-4f7b-9129-4cfd002fa5b4.png)

Maybe you need to double-check whether there are typo error of your className? Or maybe the tailwind css config file has something wrong?

**Comment by stardustdev** [comment]
This is typo issue with className. Thus closed
