### ISSUE TITLE
Hey Does anyone has faced this issue? 

### ISSUE THREAD

**Issue by hempun10** [adrianhajdin/threads#33]
<img width="918" alt="image" src="https://github.com/adrianhajdin/threads/assets/106392313/51cb0d2d-24fd-4625-a5dd-f789c36f97df">

**Comment by dophotography** [comment]
There are multiple possible options of what could happen. My recomendation is to check your code if there are no mistakes, or maybe you forgot to but { (braces) when importing components. This error just means that the object was created but not initialized.

**Comment by hempun10** [comment]
Thank you @dophotography  for your suggestion. I resolve the error. After exporting the components with it's main directory. It gets resolved.

<h1>before</h1>
// ./components/index.ts  
export \* from './MyComponent'  

//component where I will use MyComponent

import { MyComponent } from './components  

<h1>After</h1>
// component where I will use MyComponent

import { MyComponent } from './components/MyComponent
