### ISSUE TITLE
Error after Replacing the globals.css file & tailwind.config.css

### ISSUE THREAD

**Issue by Mickey374** [adrianhajdin/threads#36]
I have an issue of after configuring the components of the form from shadcn, the files[global and tailwind.config css files] that we had to replace with the appropriate files, they are giving me declarative issues and I attach a snippet of error from the Next JS on browser:
` ./app/globals.css:78:3
Syntax error: C:\Users\Mickey\OneDrive\Desktop\CODE_SPACE\threads-clone-app\application\app\globals.css The text-sm class does not exist. If text-sm is a custom class, make sure it is defined within a @layer directive.

  76 | 
  77 | .black_btn {
> 78 |   @apply rounded-full border border-black bg-black py-1.5 px-5 text-white transition-all hover:bg-white hover:text-black text-center text-sm font-inter flex items-center justify-center;
     |   ^
  79 |   
  80 | }`
  
  Now the strange thing is, it looks like it is suggesting me to wrap it around the @layer {} for all declarative css tags but when I do,
  `@layer utilities{ /*all declared css tags by adrian*/}` , it works but I cannot proceed because it is giving me errors when I try to fetch data from Clerk and populate form and the home route[http://localhost:3000/] has changed the entire layout I designed.
  
  Anyone who faced this or any help will be greatly appreciated

**Comment by AymanBoumait** [comment]
npm install tailwindcss-animate

**Comment by Mickey374** [comment]
Already have it as part 

> npm install tailwindcss-animate

Already have it as part of my package json. Even re-installing does not help.
![image](https://github.com/adrianhajdin/threads/assets/41800926/61897b41-3092-4a9b-8a49-6f5ae0cb8cd4)

**Comment by Mickey374** [comment]
Well I revoked to my previous commit on my Github repo to solve this. Layout looks clean now
