### ISSUE TITLE
fileUrl is depreciated can you please help me out

### ISSUE THREAD

**Issue by vamshi99145** [adrianhajdin/threads#40]
'fileUrl' is deprecated.ts(6385)
client.d.ts(37, 8): The declaration was marked as deprecated here.

**clinet.d.ts and error is attached**

![Screenshot (278)](https://github.com/adrianhajdin/threads/assets/77665988/89b26d2c-859d-4c1e-bdd6-00c41159fe07)
![Screenshot (279)](https://github.com/adrianhajdin/threads/assets/77665988/dc391399-8e01-45ef-95cd-3f225dcf228c)

**Comment by vamshi99145** [comment]
![Screenshot (277)](https://github.com/adrianhajdin/threads/assets/77665988/ab38bf97-3ba7-4b3e-b73b-923be4acf1e0)

**Comment by baxsm** [comment]
If you'll hover over it and read, it says "use `url` instead"
You can `url` or `fileUrl`, both works

**Comment by SkilledSparrow** [comment]
have you completed the project!?

**Comment by vamshi99145** [comment]
yes completed
