### ISSUE TITLE
original tailwind css getting overriden when initializing shadcn

### ISSUE THREAD

**Issue by dipesh2508** [adrianhajdin/threads#45]
![image](https://github.com/adrianhajdin/threads/assets/90145046/493da39a-9f62-4830-bdf3-e26bf4c12408)

**Comment by yuvraj042003** [comment]
Thanks for share your screen. the problem occours becausse you your root folder app.js and auth laout maybe same.

**Comment by dipesh2508** [comment]
> Thanks for share your screen. the problem occours becausse you your root folder app.js and auth laout maybe same.

![image](https://github.com/adrianhajdin/threads/assets/90145046/00349242-93d3-41fc-9a5a-02d6324c574b)

can you tell me exactly what is wrong here?

**Comment by yuvraj042003** [comment]
Are you push this code on github? I am unable to see your code. Plzgiveme your code

**Comment by dipesh2508** [comment]
> Are you push this code on github? I am unable to see your code. Plzgiveme your code

yes, its named circles

**Comment by yuvraj042003** [comment]
Plz send your github link
So I see your code

**Comment by yuvraj042003** [comment]
> Plz send your github repo link So I see your code

**Comment by dipesh2508** [comment]
> > Plz send your github repo link So I see your code

https://github.com/dipesh2508/circles

**Comment by dipesh2508** [comment]
so, the files actually get overridden, so we need to install shad cn before actually writing the global.css and tailwind.config.js, and in this case, need to re-write the styles in both the files.
