### ISSUE TITLE
Error: Failed to create/update user: Operation `users.findOneAndUpdate()` buffering timed out after 10000ms

### ISSUE THREAD

**Issue by Oyoskid** [adrianhajdin/threads#53]
catch (error: any) {
  throw new Error(`Failed to create/update user: ${error.message}`)
![Screenshot 2023-08-15 151945](https://github.com/adrianhajdin/threads/assets/102422453/c9db0445-06e8-408f-af96-51451828465d)

**Comment by NamanMalhotra1706** [comment]
Are You still Facing Your Error ? Is yes  Then Try to use these code and update the Params with your:-
export async function updateUser({
    userId,
    username,
    name,
    bio,
    image,
    path}:Params):Promise<void>{
    connectToDB();

   try {
    await User.findOneAndUpdate({
        id:userId},{username:username.toLowerCase(),
        name,bio,image,onboarded:true},{upsert:true});

        if(path==='/profile/edit'){
            revalidatePath(path);
        }
   } catch (error:any) {
    throw new Error(`Failed to Create/Update User: ${error.message}`)
   }
}

 If you still facing issue Please Share your AccountProfile and Post Thread tsx files where you are using this --> updateUser function

**Comment by Oyoskid** [comment]
pls any solution to this?

**Comment by Oyoskid** [comment]
Thanks
I had an error here 
![Screenshot 2023-08-16 182221](https://github.com/adrianhajdin/threads/assets/102422453/0ea5e679-29b8-4089-aa04-25a82dee2e22)
so i replaced it with
![Screenshot 2023-08-16 182309](https://github.com/adrianhajdin/threads/assets/102422453/c7ebe68d-559e-46e8-9df2-d6da6f985a30)
And it works perfectly.

**Comment by larrykings** [comment]
when configuring the .env.local file on MONGODB_URL = DONT include '< >' remove those arrow brackets when setting your password. example ( leviking:<SqlGb299n1ULf9Jk>@kings. )instead use:  (levikingi:SqlGb299n1ULf9Jk@kings.)

**Comment by Anjali4578** [comment]
> when configuring the .env.local file on MONGODB_URL = DONT include '< >' remove those arrow brackets when setting your password. example ( leviking:@kings. )instead use: (levikingi:SqlGb299n1ULf9Jk@kings.)

Thanks this worked for me :)

**Comment by LAMOUROWEN** [comment]
I get the same error. I recopied the Mongo DB URL.
![Screenshot 2023-11-20 185727](https://github.com/adrianhajdin/threads/assets/140284905/0691a575-dfa7-4ecb-98e6-fd7b8f9c31e1)
![Screenshot 2023-11-20 185741](https://github.com/adrianhajdin/threads/assets/140284905/3ee3e4dd-7f53-4950-9e30-3fb5fbed961d)

**Comment by csiber** [comment]
Check and add your IP address to MongoDB whitelist.
