### ISSUE TITLE
The topbar isn't getting its styling

### ISSUE THREAD

**Issue by Crazyhaller** [adrianhajdin/threads#6]
I have checked for typos, there is none. I dont know whats the issue
![Screenshot (58)](https://github.com/adrianhajdin/threads/assets/76851206/7edb9785-6fd7-4c43-a7cc-8d374231d219)

**Comment by Crazyhaller** [comment]
@adrianhajdin can you please help

**Comment by Dev-mininos** [comment]
you can just delete the .next file and then run npm run dev

**Comment by Crazyhaller** [comment]
> you can just delete the .next file and then run npm run dev

You mean the whole .next folder ?

**Comment by Dev-mininos** [comment]
yes,but before that shut the server

**Comment by Crazyhaller** [comment]
> yes,but before that shut the server

Yeah did that, its still not working, let me update my repo and then can you check my code if it has any error?

**Comment by Dev-mininos** [comment]
Okay,but don't expect too much from me as M just a beginner one haha

**Comment by Crazyhaller** [comment]
> Okay,but don't expect too much from me as M just a beginner one haha

That's fine, ive just updated my repo, if you go to my profile youll see Threads-X repo, can you check and tell

**Comment by Crazyhaller** [comment]
> Okay,but don't expect too much from me as M just a beginner one haha

**Comment by Dev-mininos** [comment]
Did u create the TopBar component? i think that you didn't

**Comment by Crazyhaller** [comment]
> Did u create the TopBar component? i think that you didn't

Yeah its there, I just have used the name Navbar

**Comment by Dev-mininos** [comment]
Oh okay !

**Comment by Crazyhaller** [comment]
> Oh okay !

Is the styling working for you? if yes can you share your repo link

**Comment by Crazyhaller** [comment]
> Oh okay !

Bro nvm I found the issue lol, I was using jsx instead of tsx for the file extension of the navbar component, the config file and globalscss are designed for tsx, its working now, was just a typo all this while

**Comment by Dev-mininos** [comment]
i have checked the code,seems correct but maybe the problem from the browser or idk,try to open in another browser

**Comment by Dev-mininos** [comment]
> > Oh okay !
> 
> Bro nvm I found the issue lol, I was using jsx instead of tsx for the file extension of the navbar component, the config file and globalscss are designed for tsx, its working now, was just a typo all this while

HAHAHAHAHAHA,i didn't notice that !

**Comment by Crazyhaller** [comment]
> > > Oh okay !
> > 
> > 
> > Bro nvm I found the issue lol, I was using jsx instead of tsx for the file extension of the navbar component, the config file and globalscss are designed for tsx, its working now, was just a typo all this while
> 
> HAHAHAHAHAHA,i didn't notice that !

Yeah 💀 thanks for trying to help!
