### ISSUE TITLE
Error: Failed to create thread: Thread validation failed: author:

### ISSUE THREAD

**Issue by ODOGRU77** [adrianhajdin/threads#67]
After writing the content inside the box and clicking Post Thread, below error shows up:

![image](https://github.com/adrianhajdin/threads/assets/100802815/1c0b75df-d81b-4471-a8e9-0d3f9a3fb71e)

**Comment by sXrg97** [comment]
Been stuck with this issue for a few days now :(

**Comment by sXrg97** [comment]
@ODOGRU77 fixed it! make sure to write "use server" as the first line for thread.actions.ts

**Comment by albae69** [comment]
@ODOGRU77 make sure you pass an userId with ._id like this.

<img width="420" alt="Screenshot 2023-08-30 at 13 38 05" src="https://github.com/adrianhajdin/threads/assets/52565876/aedaa651-cdd4-4004-ab7d-de977dfac767">

**Comment by ODOGRU77** [comment]
> 

You are the lifesaver man, I really appreciate it.

**Comment by HarshDubey1011** [comment]
Thanks!! but for me I have to add
```typescript
 userInfo?._id.toString()

**Comment by HoussamNaasse** [comment]
After writing the content inside the box and clicking Post Thread, below error shows up

 Error: Error creating thread: Thread validation failed: community: Path `community` is required.
    at createThread (./lib/actions/thread.action.ts:35:15)
  31 |
  32 |     } catch (error: any  ) {
> 33 |         throw new Error(`Error creating thread: ${error.message}`)
     |              ^
  34 |     }
  35 | }

Someone to help ???
