### ISSUE TITLE
Vercel Deployment Error

### ISSUE THREAD

**Issue by MarkMatute** [adrianhajdin/threads#69]
Hi there! I've got an issue and could not resolve it and block the progress for me.

1. After deploying to vercel, I can access the /sign-in and /sign-up page, but right after processing request
2. I got this FUNCTION_INVOCATION_TIMEOUT error

![image](https://github.com/adrianhajdin/threads/assets/11815770/6b31a194-dd20-43c5-b66a-075cc3294ae3)

Thanks for the tutorial though, hopefully i can resolve this.

**Comment by TyByers21** [comment]
I had the same timeout issue.  You may need to go back to your mongo db and make sure you're setup to allow ALL IP addresses to connect.

**Comment by tpratt57** [comment]
would either of you mind helping me with an issue I'm having. Opened up an issue about a week ago and haven't heard any help yet

**Comment by MarkMatute** [comment]
Yup its the MongoAtlas issue, i had to allow for access from anywhere, but again this is only for development, if for production specify specific ip address only. Cheers!

**Comment by MarkMatute** [comment]
> would either of you mind helping me with an issue I'm having. Opened up an issue about a week ago and haven't heard any help yet

whats the issue? is it the same with this one?

**Comment by tpratt57** [comment]
It is not but I'll link the issue I opened. 

https://github.com/adrianhajdin/threads/issues/68

**Comment by tpratt57** [comment]
> > would either of you mind helping me with an issue I'm having. Opened up an issue about a week ago and haven't heard any help yet
> 
> whats the issue? is it the same with this one?

Its not the same. Basically I'm having an issue with the onSubmit for onboarding. Doesn't seem to be connecting to the mongo database and I just can't figure out why. Done about all the solutions I could think of.
