### ISSUE TITLE
404 Page not found when changed link to http://localhost:3000/sign-in

### ISSUE THREAD

**Issue by ktglez02** [adrianhajdin/threads#72]
<img width="1246" alt="Screenshot 2023-09-07 at 1 12 50 PM" src="https://github.com/adrianhajdin/threads/assets/112774788/105f4747-8117-4465-9176-c3090d247231">

**Comment by ktglez02** [comment]
Due to Next js using  file system routing, my application was no working because I had an extra space behind the naming convention provided. Solved.

**Comment by yang2674** [comment]
I'm having a similar issue wherever I try to create a new user (different gmail account), I get redirected to `/sign-up` and 404: this page could not be found.

What file or folder did you find that extra space?
