### ISSUE TITLE
Unhandled Runtime Error ||  Error: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by alinasoy** [adrianhajdin/threads#75]
<img width="770" alt="Screenshot 2023-09-09 214946" src="https://github.com/adrianhajdin/threads/assets/127585848/536c5f6d-0654-4373-bd2a-f32b32969ecd">
                                                                             
Can someone help me in this issue

**Comment by amerdoahmed** [comment]
Hi I think The ID you need to past is the ID of the Thread 
you tap http://localhost:3000/thread/{ThreadID}

**Comment by yang2674** [comment]
> <img alt="Screenshot 2023-09-09 214946" width="770" src="https://user-images.githubusercontent.com/127585848/266791683-536c5f6d-0654-4373-bd2a-f32b32969ecd.png">
> Can someone help me in this issue

I have this same issue. How did you solve it?
