### ISSUE TITLE
the serverless function has timeout in vercel 

### ISSUE THREAD

**Issue by Azeem46** [adrianhajdin/threads#87]

**Comment by Azeem46** [comment]
i mean in easy words when i sign in from clerk this happens

**Comment by xql279671304** [comment]
I am also facing this problem. One of the Serverless Functions timed out, and I suspect it might be due to a MongoDB connection issue.

**Comment by Azeem46** [comment]
> I am also facing this problem. One of the Serverless Functions timed out, and I suspect it might be due to a MongoDB connection issue.

i fixed the issue you just have to go to mongodb atlas in network access your ip adddress click edit and click acces from anywhere and you are done. hope it works for you
